### PR TITLE
SSH key mode

### PR DESCRIPTION
**Pull request by jamescassell**
Partial fix for V2R1

### CODE REVIEW

**Comment by jamescassell** [comment]
Any idea why the CI failed?

**Comment by shepdelacreme** [comment]
Hmm looks like just the Docker tests that failed. I’ll dig into it this weekend.

**Comment by shepdelacreme** [comment]
LGTM...I'll review and approve once the conflicts are resolved.

**Comment by jamescassell** [comment]
Indeed, I didn't anticipate that merging the large one would conflict all the rest, since there is no logical conflict... I'll fix it up soon.

**Comment by shepdelacreme** [comment]
RHSM shouldn't fail anymore. I worked around the issue by creating a new user that could actually accept the RH terms.

**Comment by jamescassell** [comment]
conflict is period vs no period...

**Comment by jamescassell** [comment]
Looks like all tests are passing now after your workaround.  (If you're feeling ambitious, you could open a RH support case for the issue?)  Also there are no remaining conflicts on my (6) PRs so they should be merge-able.

**Pull request merged**
