### PR TITLE
yamllint implementation

### PR DESCRIPTION
**Pull request by jamescassell**
I believe this complies with the guidelines here: https://github.com/ansible/ansible-lockdown/blob/master/CONTRIBUTING.md

I left the yamllint defaults mostly in place, only deviating where it made sense.

Please don't squash.

### CODE REVIEW

**Comment by jamescassell** [comment]
here's a failed  build to prove it successfully catches yamllint errors: https://travis-ci.org/MindPointGroup/RHEL7-STIG/jobs/361840906

**Comment by shepdelacreme** [comment]
This looks good to me. Can you rebase? Thanks!

**Comment by mikerenfro** [comment]
I've grabbed the .yamllint file a day or so ago, and got emacs and flycheck to work with it. Emacs' automatic indentation isn't quite what I'd like, but at least it warns me now if something is misaligned.

**Comment by jamescassell** [comment]
rebased.

**Comment by shepdelacreme** [comment]
Ok I'm going to merge this in now.

Thanks for putting this in place @jamescassell !!

**Pull request merged**
