### PR TITLE
gather necessary facts on demand

### PR DESCRIPTION
**Pull request by jamescassell**
remove requirement to run role with 'gather_facts: yes'

### CODE REVIEW

**Comment by shepdelacreme** [comment]
My concern with this is that we now need to add tasks to gather facts each time we need them. Does doing lazy fact gathering gain you much in terms of playbook execution time?

**Comment by jamescassell** [comment]
I'd be fine with this being "not supported" but we'll take patches if they don't break anyone else... on some hardware systems, fact gathering is quite slow.

**Comment by shepdelacreme** [comment]
Ok...I'm fine with this if it saves a good amount of time during playbook run. I just never thought of fact gathering as the slow part of Ansible roles. If we go this route I think we should standardize on it.

**Comment by jamescassell** [comment]
We agreed during the meeting today that we will support 'gather_facts: no' and that we will change testing to account/test for this.

**Pull request merged**
